isolate/porto.go

https://code.google.com/archive/p/go-uuid/

"This project has been moved to https://github.com/pborman/uuid."

---

Makefile
isolate/docker/box.go
isolate/docker/box_test.go
isolate/docker/container.go
isolate/process/process_test.go
isolate/testsuite/boxsuite.go
isolate/testsuite/workersh.go

* Decode stdout/stderr format properly
* Attach to stdout/stderr
* Do not send EOF error

isolate(docker): use common TestSuite and bugfixes

---

isolate/docker/box.go
isolate/docker/container.go
isolate/docker/profile.go

profile using mapstructure to avoid unreliable type casts

isolate(docker): unpack isolate.Profile to Docker specific

---

isolate/conn_handler.go
isolate/docker/container.go
isolate/errors.go
isolate/initialdispatch.go
isolate/nonedispatch.go
isolate/process/process.go
isolate/spawndispatch.go
isolate/spooldispatch.go

+ Clean dispatch map
+ Returns all errors
+ Do not hang on `Handle`
+ Fix level of some log messages
+ And many more

Lots of bugfixes

---

cmd/stout/main.go
isolate/conn_handler.go
isolate/d_test.go
isolate/initialdispatch.go
isolate/isolate.go
isolate/profile.go
isolate/spawndispatch.go
isolate/spooldispatch.go

Print all messages to stdout (to debug). It will be eliminated
later

isolate(dispatchers): do not send messages to closed channels

---

isolate/docker/container.go
isolate/initialdispatch.go
isolate/isolate.go

docker: fix possible sending an output before

---

isolate/docker/box.go

RFCNano is not parsed properly by all Dockers

docker: fix Since argument for events

---

isolate/process/process.go
isolate/process/sysprocattr.go
isolate/process/sysprocattr_linux.go

feat(process): send SIGKILL if the daemon is dead (linux)

---

isolate/process/box.go
pkg/semaphore/semaphore.go

Limit the rate of spawning workers and decrease contention on childern map

Process rate fix

---

isolate/conn_handler.go

detached from ResponseStream.OnClose

fix(conn_handler): do not close Connection when dispatcher was

---

isolate/docker/box.go
isolate/docker/container_test.go

fix(docker): ImagePull decoder is not sensitive to \n or no-\n

---

isolate/process/box.go
isolate/process/process.go
isolate/process/sysprocattr.go
isolate/process/sysprocattr_linux.go

Process group is used to deliver signals to childs with their forks

feat(process): Set Setpgid 

---

isolate/conn_handler.go
isolate/d_test.go
isolate/initialdispatch.go
isolate/isolate.go
isolate/spawndispatch.go
isolate/spooldispatch.go

Channels > 127 were not decoder to Int64. Locally tested with uitn64

dispatcher: change int64 to uint64 for channel type

---

isolate/process/cocaine_code_storage.go

to release memory associated with msgpack.Decoder

isolate(process): do not keep Service storage alive

---

debian/changelog
isolate/initialdispatch.go
isolate/porto/box.go
isolate/porto/container.go
isolate/profile.go

Better logs from dkarpukhin

---

README.md
isolate/porto/box.go
isolate/porto/container.go

add option for set img url in porto container env property;
add log when app slooped in porto isolation;
update config example in README.md;

new option for porto box, add log and update README

---

isolate/docker/box.go
isolate/porto/box.go
isolate/porto/container.go

fix: typo fix again

---

isolate/porto/box.go
isolate/porto/container.go
stout-default.conf

add ulimits for porto isolation

---

isolate/docker/profile_decodable.go
isolate/porto/profile_decodable.go
isolate/porto/repository.go

porto: add some logs to repository and clean up

---

isolate/porto/box.go

fix whitespaces & simplify code
https://github.com/noxiouz/stout/pull/151#discussion_r192524790

fix whitespaces

---

.travis.yml
Godeps/Godeps.json
isolate/isolate.go
isolate/mtn.go
isolate/porto/box.go

Now use boltdb for keep state.
State not cleaned between restart service.
Simplify code. 
ps: That PR compiled and tested in testing environment.

New mtn state.

---

debian/control
isolate/mtn.go

[mtn] fix if statement in CountFreeAllocs()
[debian] add ca-certificates to build deps for "go get" build section

Mtn bugfix

---

isolate/porto/box.go
isolate/porto/container.go
isolate/porto/container_config.go

Two parts.
1) Check at gc state that volume is labeled as cocaine application volume.
2) Make configurable porto volume private property.

[portobox] Check that volume have cocaine app label before vunlink at GC state.

---

debian/changelog
isolate/porto/box.go
isolate/porto/profile.go
isolate/porto/profile_decodable.go
isolate/porto/profile_decodable_test.go

Add DownloadHelper as experimental feature for download layers via external program.

(portobox) Add DownloadHelper
